linux_display_server wayland

disable_ligatures never

notify_on_cmd_finish never

font_family      JetBrainsMono Nerd Font
font_size        13.0
cursor_shape     beam
cursor_blink_interval 0.5

tab_bar_style         powerline
tab_powerline_style   slanted
tab_bar_min_tabs      1

# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
#
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
