################
### MONITORS ###
################

# Monitor principal - ASUS 1440p (izquierda)
monitor = DP-1, 2560x1440@180, 0x0, 1

# Monitor secundario - LG HD (derecha)
monitor = HDMI-A-1, 1366x768@60, 2560x672, 1

workspace = DP-1, 1
workspace = HDMI-A-1, 6
